receivers:
  azureblob:
    connection_string: {{AZURE_BLOB_CONNECTION_STRING}}
    event_hub_end_point: {{EVENT_HUB_ENDPOINT}}

  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector-hub"
          scrape_interval: 5s
          metrics_path: "/metrics"
          static_configs:
            - targets: ["edgeHub:9600"]
        - job_name: "otel-collector-agent"
          scrape_interval: 5s
          metrics_path: "/metrics"
          static_configs:
            - targets: ["edgeAgent:9600"]
exporters:
  logging:
    loglevel: debug
  azuremonitor:
    instrumentation_key: {{APPINSIGHTS_INSTRUMENTATION_KEY}}


processors:
  batch:

service:
  telemetry:
      logs:
        level: "debug"
  pipelines:
    traces:
      receivers: [azureblob]
      processors: [batch]
      exporters: [logging, azuremonitor]
    logs:
      receivers: [azureblob]
      processors: [batch]
      exporters: [logging, azuremonitor]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [azuremonitor]
