#!/bin/bash

set -euxo pipefail


echo $DEPLOYMENT_FILE_PATH
testRuntimeInSeconds=40
logWindowInSeconds=20
errorsToGrep='ERR\|CRIT'


echo "Start IoT Edge solution in simulator..."
sudo -E iotedgedev start --setup --file $DEPLOYMENT_FILE_PATH

echo "Run simulator for ${testRuntimeInSeconds}s..."
sleep $testRuntimeInSeconds

echo "Check logs of last ${logWindowInSeconds}s..."

thisContainerId=$(sudo docker ps -f "name=IoTEdgeDevContainer" -q)

containerIds=$(sudo docker ps -q)

for containerId in $containerIds
do
	echo "grep $errorsToGrep in logs of $containerId..."

	errors=$(sudo docker logs --since ${logWindowInSeconds}s $containerId 2>&1 | grep $errorsToGrep || true)

	if [ -z "$errors" ]
	then
		echo "OK - Found no errors"
	else
		if [ $containerId == $thisContainerId ]
		then
			echo "Ignoring the logs generated by the container executing these tests"
		else
			echo "FAILED - Found errors in logs!"
			echo $errors
			exit 1
		fi
	fi
done