name: End to end IoT Observability Sample

trigger: none

variables:
  - group: iot-monitoring

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validation
    displayName: "Validation of ARM templates"
    jobs:
      - job: ARM_Validation
        displayName: "Validation of ARM templates"
        steps:
          - checkout: self
            name: checkout_repository
            displayName: Checkout repository

          - task: AzureResourceManagerTemplateDeployment@2
            name: arm_templates_validation
            displayName: ARM templates validation
            inputs:
              deploymentScope: "Subscription"
              azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              resourceGroupName: $(RG_NAME)
              location: $(AZURE_LOCATION)
              templateLocation: "Linked artifact"
              csmFile: "$(System.DefaultWorkingDirectory)/Templates/azuredeploy.json"
              deploymentMode: "Validation"
              overrideParameters: -environmentHashId $(IOT_ENV_SUFFIX) -templateUrl https://raw.githubusercontent.com/$(Build.Repository.Name) -branchName $(Build.SourceBranch) 


  - stage: Deployment
    displayName: "Deployment of ARM templates"
    dependsOn: Validation
    jobs:
      - job: ARM_Deployment
        displayName: "Deployment of ARM templates"
        steps:
          - checkout: self
            name: checkout_repository
            displayName: Checkout repository

          - task: AzureResourceGroupDeployment@2
            displayName: 'Azure Deployment:Create ACR'
            inputs:
              azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              resourceGroupName: $(RG_NAME)
              location: '$(AZURE_LOCATION)'
              templateLocation: 'URL of the file'
              csmFileLink: 'https://raw.githubusercontent.com/Azure-Samples/devops-iot-scripts/2281fc4e3142a2ed14655798bd3c82a44a470f86/arm-acr.json'
              overrideParameters: -registryName iotacr-$(IOT_ENV_SUFFIX) -registrySku "Basic" -registryLocation "$(AZURE_LOCATION)"
          - task: AzureResourceManagerTemplateDeployment@2
            name: arm_templates_deployment
            displayName: ARM templates deployment
            inputs:
              deploymentScope: "Subscription"
              azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              resourceGroupName: $(RG_NAME)
              location: $(AZURE_LOCATION)
              templateLocation: "Linked artifact"
              csmFile: "$(System.DefaultWorkingDirectory)/Templates/azuredeploy.json"
              deploymentMode: "Incremental"
              overrideParameters: -environmentHashId $(IOT_ENV_SUFFIX) -templateUrl https://raw.githubusercontent.com/$(Build.Repository.Name) -branchName $(Build.SourceBranch) 



    