name: End to end IoT Observability Sample

trigger: none

variables:
  - group: iot-monitoring
  - name: acr_name
    value: iotacr$(IOT_ENV_SUFFIX)
  - name: repo_name    
    value: https://raw.githubusercontent.com/$(Build.Repository.Name)
  - name: branch_name  
    value: $(Build.SourceBranch) 

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validation
    displayName: "Validation of ARM templates"
    jobs:
      - job: ARM_Validation
        displayName: "Validation of ARM templates"
      - template: templates/iac-template.yaml
        parameters:
          deployment_mode: Validation

  - stage: Deployment
    displayName: "Deployment of ARM templates"
    dependsOn: Validation
    jobs:
      - job: ARM_Deployment
        displayName: "Deployment of ARM templates"
      - template: templates/iac-template.yaml
        parameters:
          deployment_mode: Incremental

    